# Amazon books data analysis with Numpy

In [1]:
import numpy as np


## importing and convert to numpy, and inspecting

the file is downloaded from kargle(https://www.kaggle.com/sootersaalu/amazon-top-50-bestselling-books-2009-2019)
However, dataset of first col contain many commas, causing trouble when using numpy.genfromtxt(...,delimiter=',') --> more collums than expected.

To avoid this, and since I should not use  Pandas, I use csv and turn it to list of list, then apply numply.

In [2]:
import csv 
data_r=list(csv.reader(open('bestsellerswithcategories.csv'))) # list of list
print(data_r[:5]) # inspect first 5 rows
len(data_r[0]) # 1 row has 7 columns

[['Name', 'Author', 'User Rating', 'Reviews', 'Price', 'Year', 'Genre'], ['10-Day Green Smoothie Cleanse', 'JJ Smith', '4.7', '17350', '8', '2016', 'Non Fiction'], ['11/22/63: A Novel', 'Stephen King', '4.6', '2052', '22', '2011', 'Fiction'], ['12 Rules for Life: An Antidote to Chaos', 'Jordan B. Peterson', '4.7', '18979', '15', '2018', 'Non Fiction'], ['1984 (Signet Classics)', 'George Orwell', '4.7', '21424', '6', '2017', 'Fiction']]


7

In [3]:
titles=data_r[0]  # extract the title
data=data_r[1:] # the rest data to use
print(titles)

['Name', 'Author', 'User Rating', 'Reviews', 'Price', 'Year', 'Genre']


In [4]:
# tranform data to numpy array 
# column 1,2,7 are string, and the rest are numeric.at this step, all are string.
data=np.array(data,dtype=str)
data.shape # 550 rows, 7 columns

(550, 7)

In [5]:
print(data[:5])

[['10-Day Green Smoothie Cleanse' 'JJ Smith' '4.7' '17350' '8' '2016'
  'Non Fiction']
 ['11/22/63: A Novel' 'Stephen King' '4.6' '2052' '22' '2011' 'Fiction']
 ['12 Rules for Life: An Antidote to Chaos' 'Jordan B. Peterson' '4.7'
  '18979' '15' '2018' 'Non Fiction']
 ['1984 (Signet Classics)' 'George Orwell' '4.7' '21424' '6' '2017'
  'Fiction']
 ['5,000 Awesome Facts (About Everything!) (National Geographic Kids)'
  'National Geographic Kids' '4.8' '7665' '12' '2019' 'Non Fiction']]


In [6]:
# to have more human readability, I set print:
np.set_printoptions(precision=1,suppress=True)

## extract data to work on

In [45]:
#extract all col belong to numeric type from index col 2 to 5
# from titles-> column in order: User Rating', 'Reviews', 'Price', 'Year'
data_n=data[:,2:6].astype(float)
print(data_n[:20])
print(data_n.shape)

[[    4.7 17350.      8.   2016. ]
 [    4.6  2052.     22.   2011. ]
 [    4.7 18979.     15.   2018. ]
 [    4.7 21424.      6.   2017. ]
 [    4.8  7665.     12.   2019. ]
 [    4.4 12643.     11.   2011. ]
 [    4.7 19735.     30.   2014. ]
 [    4.7 19699.     15.   2017. ]
 [    4.7  5983.      3.   2018. ]
 [    4.6 23848.      8.   2016. ]
 [    4.6 23848.      8.   2017. ]
 [    4.6   460.      2.   2010. ]
 [    4.6  4149.     32.   2011. ]
 [    4.5  5153.      5.   2018. ]
 [    4.6  5013.     17.   2009. ]
 [    4.5  2313.      4.   2016. ]
 [    4.6  2925.      6.   2015. ]
 [    4.4  2951.      6.   2015. ]
 [    4.5  2426.      8.   2015. ]
 [    4.8  9198.     13.   2016. ]]
(550, 4)


## check missing value

In [8]:
#before calculating, check any missing value:
np.isnan(data_n).any()  #data has no missing value

False

## Some descriptive statistics that make sense

In [9]:
# find max and min year col =last col of data_n
print(f'year of data record from {data_n[:,-1].min()} to {data_n[:,-1].max()}')

year of data record from 2009.0 to 2019.0


In [10]:
# calculate mean of user rating, reviews, prices --> all data_n except last col
print('mean of rating, reviews, prices',data_n[:,:-1].mean(axis=0))

mean of rating, reviews, prices [    4.6 11953.3    13.1]


In [11]:
#calculate max or min of rating, reviews, prices:
print('max of rating, reviews, prices',data_n[:,:-1].max(axis=0))
print('min of rating, reviews, prices',data_n[:,:-1].min(axis=0))

#---> rating from 3.3 to 4.9
#---> reviews from 37 to 87841
#---> prices 0 to 105: some free books

max of rating, reviews, prices [    4.9 87841.    105. ]
min of rating, reviews, prices [ 3.3 37.   0. ]


In [30]:
# we want to know that if any strong relationship between price and ratings

np.corrcoef(data_n[:,2],data_n[:,0]) #--> weak negative relationship

array([[ 1. , -0.1],
       [-0.1,  1. ]])

In [31]:
# then, if strong relationship between price and review?

np.corrcoef(data_n[:,2],data_n[:,1]) #---> quite weak negative relationship

array([[ 1. , -0.1],
       [-0.1,  1. ]])

In [38]:
# cal std to have idea-> for later points
np.std(data_n[:,:-1],axis=0)

array([    0.2, 11720.5,    10.8])

## we are curious to know top 5 highest rating or reviews

In [17]:
#rating
print(data_n[np.argsort(data_n[:,0])[-5:]])
# if we want to see all other text information, book name, genres,..
print(data[np.argsort(data_n[:,0])[-5:]])

[[    4.9 14344.      5.   2019. ]
 [    4.9 14344.      5.   2017. ]
 [    4.9 21834.      8.   2014. ]
 [    4.9  7038.      7.   2012. ]
 [    4.9 21834.      8.   2016. ]]
[['Brown Bear, Brown Bear, What Do You See?' 'Bill Martin Jr.' '4.9'
  '14344' '5' '2019' 'Fiction']
 ['Brown Bear, Brown Bear, What Do You See?' 'Bill Martin Jr.' '4.9'
  '14344' '5' '2017' 'Fiction']
 ["Oh, the Places You'll Go!" 'Dr. Seuss' '4.9' '21834' '8' '2014'
  'Fiction']
 ['Goodnight, Goodnight Construction Site (Hardcover Books for Toddlers, Preschool Books for Kids)'
  'Sherri Duskey Rinker' '4.9' '7038' '7' '2012' 'Fiction']
 ["Oh, the Places You'll Go!" 'Dr. Seuss' '4.9' '21834' '8' '2016'
  'Fiction']]


In [18]:
#review
print(data_n[np.argsort(data_n[:,1])[-5:]])
print(data[np.argsort(data_n[:,1])[-5:]])

[[    4.8 61133.     11.   2018. ]
 [    4.8 61133.     11.   2019. ]
 [    4.1 79446.     18.   2015. ]
 [    4.1 79446.      7.   2016. ]
 [    4.8 87841.     15.   2019. ]]
[['Becoming' 'Michelle Obama' '4.8' '61133' '11' '2018' 'Non Fiction']
 ['Becoming' 'Michelle Obama' '4.8' '61133' '11' '2019' 'Non Fiction']
 ['The Girl on the Train' 'Paula Hawkins' '4.1' '79446' '18' '2015'
  'Fiction']
 ['The Girl on the Train' 'Paula Hawkins' '4.1' '79446' '7' '2016'
  'Fiction']
 ['Where the Crawdads Sing' 'Delia Owens' '4.8' '87841' '15' '2019'
  'Fiction']]


## if we are curious to know at what price audience start to account for 25%,50%,75% (or by quatric) by price:

In [21]:
np.percentile(data_n[:,2],25)

7.0

In [22]:
np.percentile(data_n[:,2],50)

11.0

In [24]:
np.percentile(data_n[:,2],75)

16.0

- although price range 0 to 105usd 
- but majority pay low price, we can see 75% audiences pay prices under 16 usd

## if we wonder within range mean+ or -std of price, how much data points fall in?



In [46]:
# from previous step: 
# mean price: 13.1 
# std: 10.8
a=data_n[(data_n[:,2]>2.3)&(data_n[:,2]<23.9)]
print(a)
print(len(a)) #---> 484 rows has price within our search range
print('percentage data points fall within search range',len(a)*100/550)

[[    4.7 17350.      8.   2016. ]
 [    4.6  2052.     22.   2011. ]
 [    4.7 18979.     15.   2018. ]
 ...
 [    4.7 14331.      8.   2017. ]
 [    4.7 14331.      8.   2018. ]
 [    4.7 14331.      8.   2019. ]]
484
percentage data points fall within search range 88.0
